version: '3.8' 
networks: 
  cassandra: 

services: 
  cassandra: 
    image: cassandra:5.0.2 
    container_name: cassandra 
    hostname: cassandra 
    networks: 
      - cassandra 
    ports: 
      - "9042:9042" 
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-load-keyspace:
    image: cassandra:5.0.2
    container_name: cassandra-load-keyspace
    networks: 
      - cassandra 
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ../scylla/init/init.cql:/init.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /init.cql"
